### ISSUE TITLE
Deserialization behaviour

### ISSUE THREAD

**Issue by dzubchik** [matthiasnoback/convenient-immutability#3]
First of all thank you for this useful package. We began to use it in out project but faced with a problem during object deserialization. Did you think about using this package in cases with serialization?

**Comment by matthiasnoback** [comment]
I didn't consider this, but it would be interesting to know what doesn't work. Could you provide an example, including expected and actual results? Ideally, you could also provide a test case which shows the problem.

**Comment by dzubchik** [comment]
Here a code example which covers this issue:

```
<?php


namespace ConvenientImmutability\Test;

use ConvenientImmutability\Test\Resources\Foo;

class SerializationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @test
     */
    public function it_should_be_same_after_serialization()
    {
        $foo = new Foo();
        $foo->bar = 1;
        $foo->baz = 2;

        $serializedValue = serialize($foo);
        $deSerializedValue = unserialize($serializedValue);

        $this->assertSame($deSerializedValue->bar, $foo->bar);
        $this->assertSame($deSerializedValue->baz, $foo->baz);
    }
}
```

This could be fixed by adding __wakeup behavior the same as in constructor.

**Comment by matthiasnoback** [comment]
Thanks! I see. I'm guessing this might be quite a simple change. Do you feel ready to create a PR to add this functionality?

**Comment by dzubchik** [comment]
Yes, I will send a PR!

**Comment by matthiasnoback** [comment]
Hey!
So, I may not have been entirely clear. I was looking for a second run of tests, exactly the same as those already defined in the `ImmutableTraitTest` class. You could accomplish this by making each test method use a [data provider](https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers). Such a data provider could return either a fresh object or an object that has been populated with data, then serialized and unserialized. This should prove that none of the behaviors get lost because of the serialization process.
Would you like to try to implement this?

**Comment by dzubchik** [comment]
I will add this test.

**Comment by dzubchik** [comment]
@matthiasnoback , I don't understand how different test classes can use shared data provider. Maybe I misunderstood you again, so please give a an example if it possible. PR is updated.

**Comment by matthiasnoback** [comment]
Ah, you could demonstrate this in the same test case, e.g.

```php
/**
 * @dataProvider objectProvider
 */
public function some_test(Foo $foo)
{
    // all the existing test cases should accept the argument, instead of creating a new Foo
}

public function objectProvider()
{
    // to run tests with a fresh Foo instance
    $foo = new Foo();

    // to run tests with an unserialized Foo instance
    $foo = unserialize(serialize($foo));

    return [
        [$foo],
        [$unserializedFoo]
    ];
}
```

Does that make sense?

**Comment by dzubchik** [comment]
@matthiasnoback , as you can see, it is not expected behavior. So I propose to revert last commit and leave it, because we clearly see, that object **with data** has the same behavior before and after serialization/deserealization. What do you think?

**Comment by matthiasnoback** [comment]
I don't know what you mean since I don't see what is not expected behavior. Also, all the tests seem to be passing. Could you explain a bit more?

**Comment by matthiasnoback** [comment]
See #4. Thanks again!

**Comment by dzubchik** [comment]
@matthiasnoback , sorry for disturbing you about this again, but, as you can see, after last commit we have not test [ necessary lines](https://coveralls.io/builds/10811905/source?filename=src%2FImmutable.php#L61) of code - __wakeup method (code coverage decreased). Previous commit covers it, but it requires separate test cases because serialization/deserialization should be performed on object with some data (not default), after we change some property value. It can be easily done, be adding one more test case, as I [wrote](https://github.com/dzubchik/convenient-immutability/commit/547e92b2c48d46752fad915b4d74508ab1e69a77) from the very beginning. Do you want me to send pull request?

**Comment by matthiasnoback** [comment]
Okay, I'm sorry, yes, sure thing - it needs a separate test. You could simply add methods to the existing test class by the way. Thanks!
